name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install PHP 8.4 and extensions
        run: |
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install -y php8.4 php8.4-cli php8.4-common php8.4-intl php8.4-mbstring php8.4-xml php8.4-curl php8.4-zip
          php -v

      - name: Install Composer
        run: |
          EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
              >&2 echo 'ERROR: Invalid Composer installer signature'
              rm composer-setup.php
              exit 1
          fi
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          rm composer-setup.php
          composer -V

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist    
      
      - name: Validate certificates
        run: php cli.php ValidCertificates

      - name: Validate robots.txt and sitemap
        run: php cli.php RobotsAndSitemap

      - name: Find feeds
        run: php cli.php FindFeed

      - name: Export for web
        run: php cli.php ExportForWeb
      
      #- name: Save to archive
      #  run: php cli.php SaveToArchive

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    permissions:
      contents: 'read'
      pages: 'write'
      id-token: 'write'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4